### PR TITLE
Folder support added to logStreams

### PR DESCRIPTION
**Pull request by eeertekin**
Sample configuration :

xports.config = {
  nodeName: "RDS",
  logStreams: {
    eee : [
       **"/www/v3/eee/logs/",**
    ]
  },
  server: {
    host: '0.0.0.0',
    port: 28777
  }
}

### CODE REVIEW

**Comment by zdnet** [comment]
+1

**Comment by skantana** [comment]
+1

**Comment by php-cpm** [comment]
+1

**Comment by msmathers** [comment]
Resolved in v0.4.3

**Pull request closed without merging**
